spring.application.name=imrf-backend

server.port=8080

spring.data.mongodb.uri=mongodb+srv://kumpatipremanth635_db_user:Prem2004@imrf-cluster.v4bcomm.mongodb.net/?appName=imrf-cluster

spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb=INFO